### ISSUE TITLE
Hello could you please provide the code just for amplification module，i'm a little confused this this part just reading paper,thanks

### ISSUE THREAD

**Issue by woaiwojia4816294** [MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time#11]

**Comment by MohitLamba94** [comment]
It is already there starting from

line https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/blob/1841ff50f23eb5ae9e6d54a862059e173f5d618e/common_classes.py#L11

till 

line https://github.com/MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time/blob/1841ff50f23eb5ae9e6d54a862059e173f5d618e/common_classes.py#L36
