### ISSUE TITLE
test demo

### ISSUE THREAD

**Issue by kkllww** [MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time#15]
Hello, may I ask which data set the model loaded in the demo is trained from, how big is the tested original image, and how generic the model is？

**Comment by MohitLamba94** [comment]
For demo network in the github repository we randomly sampled some 180 images from Sony SID dataset with 0.1 exposure with 00 ids.

for full training include all exposures and then test on all exposures with all ids. Exclude the test images mentioned in the SID repository.
