### ISSUE TITLE
Great work! Since your paper compare your method with LDC, I wonder where the code of LDC is.

### ISSUE THREAD

**Issue by leonmakise** [MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time#3]
**LDC Learning to restore low-light images via decomposition-andenhancement CVPR2020**

I cannot find its code. But you say that LDC [65] has publicly available code.

Can you point out its url or offer your reimplementation?

Thanks a lot!

**Comment by MohitLamba94** [comment]
It is available on the personal website of Dr. Rynson.

https://drive.google.com/drive/folders/1L3RDbd3sk_TcMTrSmZXn8KLg8opjOjf0

**Comment by leonmakise** [comment]
Thanks! I have also found this code. However, it seems that this code is only used for testing those RGB inputs with a certain size. How can you train it for raw data inputs?

**Comment by leonmakise** [comment]
> It is available on the personal website of Dr. Rynson.
> 
> https://drive.google.com/drive/folders/1L3RDbd3sk_TcMTrSmZXn8KLg8opjOjf0

Thanks! I have also found this code. However, it seems that this code is only used for testing those RGB inputs with a certain size. How can you train it for raw data inputs?

**Comment by MohitLamba94** [comment]
> > It is available on the personal website of Dr. Rynson.
> > https://drive.google.com/drive/folders/1L3RDbd3sk_TcMTrSmZXn8KLg8opjOjf0
> 
> Thanks! I have also found this code. However, it seems that this code is only used for testing those RGB inputs with a certain size. How can you train it for raw data inputs?

We had explicitly mailed the authors for the code to process RAW images but dint get any reply. So you will have to slightly modify whatever code the authors have made public if you wish to work with RAW images.

**Comment by leonmakise** [comment]
> > > It is available on the personal website of Dr. Rynson.
> > > https://drive.google.com/drive/folders/1L3RDbd3sk_TcMTrSmZXn8KLg8opjOjf0
> > 
> > 
> > Thanks! I have also found this code. However, it seems that this code is only used for testing those RGB inputs with a certain size. How can you train it for raw data inputs?
> 
> We had explicitly mailed the authors for the code to process RAW images but dint get any reply. So you will have to slightly modify whatever code the authors have made public if you wish to work with RAW images.

Thanks a lot! According to your paper, you also retrain DCE on raw data. I wonder how you treat that network or how to modify it? From my perspective, I thnik it would be better to pack raw to 4 channels with half resolution and output a tensor with 12 channels, then perform a pixel_shuffle to get the final RGB result?
Many thanks to your replies!

**Comment by MohitLamba94** [comment]
Yes, current convolution kernels assume that spatially pixels belong to same color. Only along the channels dimension may pixels belong to different colors. Infact we tried both as you suggested breaking into 4 channels helps.

**Comment by JayYe99** [comment]
The discussion of you guys help me a lot. One quick question here: Are the restored results generated by approaches trained on RAW images much better than those generated by approaches trained on RGB images? Or can I say that RAW images have much more potential information beneficial to image restoration comparing to RGB images?

**Comment by MohitLamba94** [comment]
Working directly on RAW images gives 7-10 dB higher PSNR.

**Comment by JayYe99** [comment]
> Working directly on RAW images gives 7-10 dB higher PSNR.

Got it! Thx for the early reply! Best wishes~
