### ISSUE TITLE
SID dataset training

### ISSUE THREAD

**Issue by xuwanyan1998** [MohitLamba94/Restoring-Extremely-Dark-Images-In-Real-Time#6]
Very comprehensive and brilliant work!But I have a problem when I try to retrain the Network in your project,I found that when you choose the train&test files in SID Sony Dataset, you just choose '0*_00_0.1s.ARW','1*_00_0.1s.ARW','2*_00_0.1s.ARW' and corresponding long exposure raw image as your dataset,which cause that you just use 181 pairs data for train and 50 pairs data for test,and ignore other exposure time low light image such as '*0.04s.ARW','*0.033s.ARW'

**Comment by MohitLamba94** [comment]
This i did due to limited RAM of just 64GB. If you have even lesser CPU RAM yo will have to further shrink down number of images loaded into CPU RAM. If you have more say 256 GB RAM you can load more images.

**Comment by lzg1988** [comment]
It is not the issue of RAM. You are using more training data and less challenging exposure(0.04s+0.033s)data? How can you compare with sid and did when you use totally diffirent dataset for training and testing?????????
